#!/bin/bash

cur_dir="$(dirname "$0")"

src_file="$1"
dst_file="$2"

if [ -z "$src_file" ]; then
    echo >&2 "Usage: $0 source_file.xapk [destination_file.apk]"
    exit 1
fi

shopt -s nocasematch
[ -z "$dst_file" ] && dst_file="${src_file/%.xapk/.apk}"
shopt -u nocasematch

"$cur_dir/third_party/apkeditor" m -i "$src_file" -o "$dst_file"


